### ISSUE TITLE
Empty Comment Lines When Viewing a PR

### ISSUE THREAD

**Issue by parhamdoustdar** [charignon/github-review#15]
First off, thanks a lot for your great work on fixing #5!

I've enabled the feature already, and I'm trying to review this PR: https://github.com/bookingcom/shipper/pull/70

If you try reviewing that, you'll see a lot of lines like this:

```
~ Reviewed by @isutton[COMMENTED]: 
~ Reviewed by @isutton[COMMENTED]: 
~ Reviewed by @isutton[COMMENTED]: 
~ Reviewed by @isutton[COMMENTED]: 
```

Strangely, there's also a line like this:

```
~ Reviewed by @icanhazbroccoli[COMMENTED]: 
```

Maybe this is some sort of a reply, since @icanhazbroccoli is the author and hasn't actually reviewed his own PR?

Thanks for making my life easier! :-)

**Comment by charignon** [comment]
1) You found an issue. When someone is submitting a review that is just comments (as opposed to approve and reject), they are not forced to set a top level message. In this PR that's what the people did. That's a workflow that I am not used to seeing and right now that's true that it looks odd when using `github-review`. We can change the behavior to be:
`~ Reviewed by @isutton[COMMENTED]:  Left comments inline, no top level message`

2) You can actually review your own PR, but not approve and reject it. Are you sure he didn't review his own PR?

**Comment by parhamdoustdar** [comment]
* What do you think about filtering those out completely? As in, not mentioning the lines with `@isutton` at the top?
* I double-checked, and I still don't see him reviewing his own PR. Can you check to see if I'm doing this right, just to be sure?

**Comment by charignon** [comment]
1) Okay, I am fine with doing that, will update the feature.
2) The API claims that he did so, I looked at the response, maybe the reply to comments count as a top level review?

**Comment by parhamdoustdar** [comment]
* Thanks!
* Yeah, makes sense. Or rather, maybe replying to inline review comments is
also counted as a review if that makes sense. In other words, I think if
you filter out the reviews that don't have a top-level comment, things
would just fall into place.
