### ISSUE TITLE
Add reviewers from Emacs

### ISSUE THREAD

**Issue by matthew-piziak** [charignon/github-review#18]
When I create a pull request from Emacs (personally I like to do `C-c C-n` from `forge`), it would also be nice if I could immediately request reviewers. 

Similarly, it would be nice to be able to assign myself to the PR.

**Comment by charignon** [comment]
Hi, thanks for the feedback! Unfortunately, I don't think that this is in scope for the `github-review` package. The goal of this package is only to provide a way to review code from within emacs. You could suggest it in forge though, that would be great!

**Comment by matthew-piziak** [comment]
Done, thank you! https://github.com/magit/forge/issues/82
