### ISSUE TITLE
 Error talking to GitHub 

### ISSUE THREAD

**Issue by agzam** [charignon/github-review#19]
On attempt to `github-review-comment`, throws "Error talking to GitHub"

**Comment by agzam** [comment]
Sorry, about to add something but posted it too prematurely. This isn't a bug.

**Comment by grischoun** [comment]
I actually have this issue. Any hint on how to solve it?

**Comment by grischoun** [comment]
Sorry, it actually works on a repo that I fully control. It does not on another repo where I guess I am lacking some rights.
