### ISSUE TITLE
review feedback displayed in reverse order

### ISSUE THREAD

**Issue by zenspider** [charignon/github-review#22]
See https://github.com/seattlerb/minitest/pull/793 for an example

It would be nice if, on the overview page, the comments read top-to-bottom with what was written up. They seem to submit from top-to-bottom and as such, read upside down (because newest first?).

**Comment by charignon** [comment]
That's correct, it is a valid issue, feel free to send a PR to fix it, otherwise I can take a look at it in the next month.

**Comment by charignon** [comment]
@zenspider let me know if this is still an issue, it should be fixed in the latest version
