### ISSUE TITLE
"Error talking to GitHub"

### ISSUE THREAD

**Issue by grischoun** [charignon/github-review#27]
I receive the "Error talking to GitHub" message when I try to submit a review on a repository where I am given "maintainer" rights.

Notice that when I am testing against a repository that I created and I own, everything works fine.

**Comment by charignon** [comment]
Thanks for the bug report! Could you check that you aren't hitting #25 ? 
I filed #28 to improve the error messages.

**Comment by grischoun** [comment]
Thanks for your message.
No I am not hitting #25.

**Comment by charignon** [comment]
I haven't been able to reproduce, can you give me a step by step way to reproduce this issue?

**Comment by syzygyzer** [comment]
I ran into the same issue trying to post a comment, after I had already posted a few successfully to the same repo (I was just testing out functionality). Restarting emacs fixed it for me and I haven't run into it again. Will be back here if it happens in a reproducible fashion.

**Comment by charignon** [comment]
Please reopen if you see it again after the fix in #51
