### ISSUE TITLE
Work with Github Enterprise

### ISSUE THREAD

**Issue by logc** [charignon/github-review#29]
My Magit Forge is configured to work with my company's Github Enterprise. I just created a token for `github-review` and stored it in `~/.authinfo.gpg`, but trying to `github-review-forge-pr-at-point` (when on a Forge PR) sends me into the buffer to interactively create a token on "api.github.com".

**Comment by charignon** [comment]
Thanks for the bug report. I will be looking into it in January. If anyone has time to get to it before, feel free to send a PR.

**Comment by charignon** [comment]
Workaround: with customize, set the value of `github-review-host` to match your GHE api server. We could improve `github-review-forge-pr-at-point` to pass in the api host and bypass the value of `github-review-host`, I will be looking into it later this month.
