### ISSUE TITLE
deleting lines starting with `--` breaks submission

### ISSUE THREAD

**Issue by symbiont-sam-halliday** [charignon/github-review#30]
In Haskell line comments are

```haskell
-- this is a comment
```

and if a line is removed in a diff it looks like

```diff
--- this is a comment
```

which confuses the filename detector logic in `github-review-non-null-filename-hunk-line`

**Comment by charignon** [comment]
Thank you very much for the bug report! I will be looking into it in January. Feel free to send a PR before that and I would be happy to review it :)

**Comment by charignon** [comment]
This should be fixed after my PR, feel free to let me know if you can repro @symbiont-sam-halliday

**Comment by charignon** [comment]
Feel free to reopen this if it is still an issue
