### ISSUE TITLE
doom emacs install

### ISSUE THREAD

**Issue by syzygyzer** [charignon/github-review#35]
The instructions in the readme say to add:

```
(package!
 github-review
 :recipe
    (:fetcher github
     :repo "charignon/github-review"
     :files ("github-review.el")))
```

to your doom config. I'm running the development branch on emacs 28 and this produced an error for me:

```
Type: doom-package-error
  Message:
    Error with packages
  Data:
    (:private . packages)
    (doom-package-error "github-review" . "Keyword argument :fetcher not one of (:local-repo :files :flavor :no-build :type :repo :host :branch :remote :nonrecursive :fork :depth)")
```

Henrik (doom maintainer) says to use `:host` instead:

```
(package!
 github-review
 :recipe
    (:host github
     :repo "charignon/github-review"
     :files ("github-review.el")))
```
This fixed the error.

**Comment by charignon** [comment]
Good point, I will update the instructions. Also it seems that it has been included in doom emacs when you use magit https://github.com/hlissner/doom-emacs/blob/2441b447897e561a29d263e204e5700bf5f920d9/modules/tools/magit/packages.el
