### ISSUE TITLE
Deleted files have the header `/dev/null`

### ISSUE THREAD

**Issue by floscr** [charignon/github-review#4]
Deleted files seem to have the header `/dev/null`

<img width="215" alt="screen shot 2019-02-27 at 11 21 35" src="https://user-images.githubusercontent.com/1898374/53483473-dded0100-3a81-11e9-8c2f-f31bd22cf76e.png">

**Comment by charignon** [comment]
Thanks for the bug report! I indeed am able to reproduce the issue: when commenting on deleted file content the payload is incorrect. I will write a test and fix it when I get a chance.
