### ISSUE TITLE
Support diff-goto-source with github-review-forge-pr-at-point

### ISSUE THREAD

**Issue by rvl** [charignon/github-review#41]
It would be nice if `diff-goto-source` (`C-c C-c`) worked when this is invoked from `github-review-forge-pr-at-point`. All it needs to do is set the current directory to the git working tree in the `diff-mode` buffer. In many cases it does not matter too much whether the user has the "correct" branch is checked out - it just needs to be close.

**Comment by charignon** [comment]
That is a great idea, thanks for the suggestion. I will be looking into it when I have time, otherwise feel free to contribute the change if you have the expertise and time @rvl.

**Comment by rvl** [comment]
I'm not sure whether I have either of those, but once I have used github-review a bit more, I might have a go.

**Comment by charignon** [comment]
Try this:

```diff
From 967edd5a09f2903074d3a66253c0c5f8676bfd26 Mon Sep 17 00:00:00 2001
From: Laurent Charignon <l.charignon@gmail.com>
Date: Fri, 13 Mar 2020 22:17:20 -0700
Subject: [PATCH] Add advice to diff-goto-source for forge PRs

---
 github-review.el | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/github-review.el b/github-review.el
index 594993a..659cf5d 100644
--- a/github-review.el
+++ b/github-review.el
@@ -525,6 +525,9 @@ See ‘github-review-start’ for more information"
                        (github-review-a-assoc 'repo  name)
                        (github-review-a-assoc 'apihost apihost)
                        (github-review-a-assoc 'num   number))))
+    (setq forge-current-dir default-directory)
+    (defadvice diff-goto-source (before set-dir-to-current-dir activate)
+      (setq default-directory forge-current-dir))
     (github-review-start-internal pr-alist)))
 
 ;;;###autoload
-- 
2.25.0
```
I tried it and it works for me @rvl.
If this works for you we can work on productionizing it.

**Comment by charignon** [comment]
@parhamdoustdar you may be interested in this feature too

**Comment by rvl** [comment]
Yes @charignon that patch works great!

**Comment by charignon** [comment]
I don't quite know when to set the default-directory back to its previous value and if we should even do it. Does anyone know?

**Comment by rvl** [comment]
In the documentation for default-directory it says that it automatically becomes permanently buffer-local when set. So it's not the global emacs process working directory. I think it should set default-directory to the when setting up the diff buffer.

**Comment by charignon** [comment]
So we could memorize if the user got to the diff buffer from forge and set the default-directory in that case but not change it in any other case. Does that seem right @rvl?
