### ISSUE TITLE
Re: Configuration - What access does github-review need?

### ISSUE THREAD

**Issue by jtpavlock** [charignon/github-review#45]
Referring to https://github.com/charignon/github-review#configuration

What levels of access should I permit on my github token for github-review to work?

**Comment by charignon** [comment]
I think you need just public_repo and repo status, let me know if that seems to be an issue:

<img width="596" alt="Screen Shot 2020-07-23 at 12 08 30 PM" src="https://user-images.githubusercontent.com/634929/88328418-4541cb80-ccdd-11ea-922d-b66e50294974.png">

**Comment by jtpavlock** [comment]
Thanks for the response. I ended up just using the same token as magit forge which uses

> `repo` grants full read/write access to private and public repositories.
> `user` grants access to profile information.
> `read:org` grants read-only access to organization membership.

And got it working, so it's at least those or a subset of those as you suggest 😅
