### ISSUE TITLE
docs need clarification (or code needs changing?)

### ISSUE THREAD

**Issue by slackorama** [charignon/github-review#68]
Maybe it's just my setup at work with github enterprise.

I set my `github-review-host` to `"git.mycompany.com"` but I needed to use `api.git.mycompany.com` in order to get things to work. 

Otherwise, it bombed out with an unhelpful `Got an error from the GitHub API (wrong-type-argument stringp nil)!` even though it never sent the request as `ghub--auth` was erroring out.

Actually, maybe there's a bug somewhere. Because when I call `gitreview-submit-commet` it uses `git.mycompany.com` as the host.

**Comment by charignon** [comment]
You should indeed use the API endpoint in order to get things to work. So you say that if you set `github-review-host` to `api.git.mycompany.com` it makes the request against `git.mycompany.com`?

**Comment by charignon** [comment]
I can definitely add an example to the doc to hint at the fact that one must use `api.git.mycompany.com` and not `git.mycompany.com` but before I want to check that it works well for you (it works for me).

**Comment by slackorama** [comment]
Thanks! 

If I set my host to `api.git.mycompany.com` doing a review/comment from a forge request works without a hitch.

**Comment by charignon** [comment]
I updated the readme and the docs and will merge the change soon after the tests pass.
