### ISSUE TITLE
Should start at the beginning of the buffer

### ISSUE THREAD

**Issue by agzam** [charignon/github-review#74]
Currently, when it starts and generates diff-buffer, it puts the cursor at the end of the buffer. I think it should start at the top.

**Comment by agzam** [comment]
Temporarily I put this workaround in my config:

    (defun github-review--after-save-diff (pr-alist diff)
      (let-alist pr-alist
        (with-current-buffer
         (format "%s___%s___%s___%s.diff" .owner .repo .num .sha)
         (goto-line 1))))

    (advice-add 'github-review-save-diff :after 'github-review--after-save-diff)

**Comment by charignon** [comment]
That's a good point, feel free to send me a PR and I will merge it.
